let API_URL= import.meta.env.VITE_API_URL
let DOMAIN_URL=import.meta.env.VITE_DOMAIN_URL
let QR_WALLET_ADDRESS=import.meta.env.VITE_QR_WALLET_ADDRESS
API_URL=String(API_URL)
DOMAIN_URL=String(DOMAIN_URL)
QR_WALLET_ADDRESS=String(QR_WALLET_ADDRESS)






export{API_URL,DOMAIN_URL,QR_WALLET_ADDRESS}